# Generated by Django 4.0.6 on 2022-08-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_recipient_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
