# Generated by Django 4.0.6 on 2022-08-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_auth', '0002_alter_emailverificationtoken_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverificationtoken',
            old_name='token_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='expiringtokenauthentication',
            old_name='token_key',
            new_name='key',
        ),
    ]
