name: Run lint on PR to main
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      #check out repository
      - uses: actions/checkout@v3
      
      #set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Get Pip
        run: |
          python -m pip install --upgrade pip

      - name : Download dependencies
        run: |
          pip install -r requirements.txt

      - name: Get pylint
        run: |
          pip install pylint==2.10.2

      - name: Get pylint-django
        run: |
          pip install pylint-django==2.4.4

      - name: Run Linter
        run: |
          shopt -s extglob
          pylint --load-plugins pylint_django --django-settings-module=df.settings --ignore=migrations --rcfile=.pylintrc ./!(*.drawio|*.yml)
        env:
          SECRET_KEY: aaaa
          DEBUG: false
          FRONT_END_URL: aaaa
          ENGINE: django.db.backends.postgresql
          NAME: aaaa
          HOST: aaaa
          USER: aaaa
          PASSWORD: aaaa
          PORT: 5432
          ALLOWED_HOSTS: aaaa.com
          CORS_ALLOWED_ORIGINS: aaaa.com
          SUPER_USER_EMAIL: example@example.com
          SUPER_USER_FIRST: aaaa
          SUPER_USER_LAST: aaaa
          SUPER_USER_PASSWORD: aaaa
